### ISSUE TITLE
Can you post an installation video? 

### ISSUE THREAD

**Issue by Fifar4** [AnthonyKNorman/Xiaomi_LYWSD03MMC_for_HA#8]
Everything looks like Chinese.
I have no experience in MQTT
I will pay you if it works :)

**Comment by AnthonyKNorman** [comment]
Hi
I'm sorry, but this sort of project is for people with some experience of Micropython and IoT. I would suggest you try some of the many Micropython tutorials on the internet, such as those from Adafruit.
