### ISSUE TITLE
Gaps in mac address for device id

### ISSUE THREAD

**Issue by isoinh** [AnthonyKNorman/Xiaomi_LYWSD03MMC_for_HA#9]
I'm getting a gap in my mac address:
`GAP procedure initiated: connect; peer_addr_type=0 peer_addr=a4:c1:38:0f:39:c8 scan_itvl=16 scan_window=16 itvl_min=24 itvl_max=40 latency=0 supervision_timeout=256 min_ce_len=16 max_ce_len=768 own_addr_type=0
self.connected False
IRQ peripheral connect
GATT procedure initiated: write; att_handle=70 len=3
.A gattc_write() has completed - status. 0 70 0
A peripheral has sent a notify request. 0 54 b'H\n-\xd5\n'
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=400 itvl_max=400 latency=0 supervision_timeout=600 min_ce_len=16 max_ce_len=768
write ok
.......A peripheral has sent a notify request. 0 54 b'H\n-\xd5\n'
Data received
GAP procedure initiated: terminate connection; conn_handle=0 hci_reason=19
.connected peripheral has disconnected. 0 0 a4:c1:38:0f:39:c8
{"temperature": "26.32", "humidity": "45", "batt": "67", "voltage": "2.773"}
b'espble/a4c138 f39c8'
`

And:
`GAP procedure initiated: connect; peer_addr_type=0 peer_addr=a4:c1:38:1b:74:08 scan_itvl=16 scan_window=16 itvl_min=24 itvl_max=40 latency=0 supervision_timeout=256 min_ce_len=16 max_ce_len=768 own_addr_type=0
self.connected False
IRQ peripheral connect
GATT procedure initiated: write; att_handle=56 len=2
.A gattc_write() has completed - status. 0 56 0
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=12 itvl_max=24 latency=0 supervision_timeout=90 min_ce_len=16 max_ce_len=768
write ok
GATT procedure initiated: write; att_handle=70 len=3
.GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=400 itvl_max=400 latency=0 supervision_timeout=600 min_ce_len=16 max_ce_len=768
A gattc_write() has completed - status. 0 70 0
write ok
...A peripheral has sent a notify request. 0 54 b'\xbe\n-+\x0b'
Data received
GAP procedure initiated: terminate connection; conn_handle=0 hci_reason=19
.connected peripheral has disconnected. 0 0 a4:c1:38:1b:74:08
{"temperature": "27.5", "humidity": "45", "batt": "76", "voltage": "2.859"}
b'espble/a4c1381b74 8'
`

I've already tried VladoPortos fix in pull request but it didn't help for my issue.
Does anybody have any suggestion howto fix this?

**Comment by AnthonyKNorman** [comment]
Hi
Try the new version of MQTT.py that I have just published and let me know how you get on.

**Comment by isoinh** [comment]
Hummm... I'm pretty new with these things and might be my stupidity but can't seem to find the new version.
`Showing 0 changed files with 0 additions and 0 deletions` for `b9edbb2` commit.

**Comment by AnthonyKNorman** [comment]
No. Me that's stupid. It's not there.  I'll sort it out in the morning.

**Comment by AnthonyKNorman** [comment]
please try new mqtt.py now.

**Comment by isoinh** [comment]
Works like a charm! Thank you!
